// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package models

import (
	"database/sql"
)

type App struct {
	ID                   int32           `json:"id"`
	Name                 sql.NullString  `json:"name"`
	Path                 sql.NullString  `json:"path"`
	BundleExecutable     sql.NullString  `json:"bundle_executable"`
	BundleIdentifier     sql.NullString  `json:"bundle_identifier"`
	BundleName           sql.NullString  `json:"bundle_name"`
	BundleShortVersion   sql.NullString  `json:"bundle_short_version"`
	BundleVersion        sql.NullString  `json:"bundle_version"`
	BundlePackageType    sql.NullString  `json:"bundle_package_type"`
	Environment          sql.NullString  `json:"environment"`
	Element              sql.NullString  `json:"element"`
	Compiler             sql.NullString  `json:"compiler"`
	DevelopmentRegion    sql.NullString  `json:"development_region"`
	DisplayName          sql.NullString  `json:"display_name"`
	InfoString           sql.NullString  `json:"info_string"`
	MinimumSystemVersion sql.NullString  `json:"minimum_system_version"`
	Category             sql.NullString  `json:"category"`
	ApplescriptEnabled   sql.NullString  `json:"applescript_enabled"`
	Copyright            sql.NullString  `json:"copyright"`
	LastOpenedTime       sql.NullFloat64 `json:"last_opened_time"`
	CreatedAt            sql.NullTime    `json:"created_at"`
	UpdatedAt            sql.NullTime    `json:"updated_at"`
}
