// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package models

import (
	"database/sql"
)

type App struct {
	ID                   int32           `json:"id"`
	Name                 sql.NullString  `json:"name"`
	Path                 sql.NullString  `json:"path"`
	BundleExecutable     sql.NullString  `json:"bundle_executable"`
	BundleIdentifier     sql.NullString  `json:"bundle_identifier"`
	BundleName           sql.NullString  `json:"bundle_name"`
	BundleShortVersion   sql.NullString  `json:"bundle_short_version"`
	BundleVersion        sql.NullString  `json:"bundle_version"`
	BundlePackageType    sql.NullString  `json:"bundle_package_type"`
	Environment          sql.NullString  `json:"environment"`
	Element              sql.NullString  `json:"element"`
	Compiler             sql.NullString  `json:"compiler"`
	DevelopmentRegion    sql.NullString  `json:"development_region"`
	DisplayName          sql.NullString  `json:"display_name"`
	InfoString           sql.NullString  `json:"info_string"`
	MinimumSystemVersion sql.NullString  `json:"minimum_system_version"`
	Category             sql.NullString  `json:"category"`
	ApplescriptEnabled   sql.NullString  `json:"applescript_enabled"`
	Copyright            sql.NullString  `json:"copyright"`
	LastOpenedTime       sql.NullFloat64 `json:"last_opened_time"`
	CreatedAt            sql.NullTime    `json:"created_at"`
	UpdatedAt            sql.NullTime    `json:"updated_at"`
}

type OsVersion struct {
	ID               int32          `json:"id"`
	Name             string         `json:"name"`
	Version          string         `json:"version"`
	Major            sql.NullInt32  `json:"major"`
	Minor            sql.NullInt32  `json:"minor"`
	Patch            sql.NullInt32  `json:"patch"`
	Build            sql.NullString `json:"build"`
	Platform         sql.NullString `json:"platform"`
	PlatformLike     sql.NullString `json:"platform_like"`
	Codename         sql.NullString `json:"codename"`
	Arch             sql.NullString `json:"arch"`
	Extra            sql.NullString `json:"extra"`
	InstallDate      sql.NullInt64  `json:"install_date"`
	Revision         sql.NullInt32  `json:"revision"`
	PidWithNamespace sql.NullInt32  `json:"pid_with_namespace"`
	MountNamespaceID sql.NullString `json:"mount_namespace_id"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
}

type OsqueryInfo struct {
	ID            int32          `json:"id"`
	Pid           sql.NullInt32  `json:"pid"`
	Uuid          sql.NullString `json:"uuid"`
	InstanceID    sql.NullString `json:"instance_id"`
	Version       sql.NullString `json:"version"`
	ConfigHash    sql.NullString `json:"config_hash"`
	ConfigValid   sql.NullInt32  `json:"config_valid"`
	Extensions    sql.NullString `json:"extensions"`
	BuildPlatform sql.NullString `json:"build_platform"`
	BuildDistro   sql.NullString `json:"build_distro"`
	StartTime     sql.NullInt32  `json:"start_time"`
	Watcher       sql.NullInt32  `json:"watcher"`
	PlatformMask  sql.NullInt32  `json:"platform_mask"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}
