// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: os_version.sql

package models

import (
	"context"
)

const getOSDetails = `-- name: GetOSDetails :one
SELECT 
    id,
    name,
    version,
    major,
    minor,
    patch,
    build,
    platform,
    platform_like,
    codename,
    arch,
    extra,
    install_date,
    revision,
    pid_with_namespace,
    mount_namespace_id,
    created_at,
    updated_at
FROM
    os_version
`

func (q *Queries) GetOSDetails(ctx context.Context) (OsVersion, error) {
	row := q.queryRow(ctx, q.getOSDetailsStmt, getOSDetails)
	var i OsVersion
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Major,
		&i.Minor,
		&i.Patch,
		&i.Build,
		&i.Platform,
		&i.PlatformLike,
		&i.Codename,
		&i.Arch,
		&i.Extra,
		&i.InstallDate,
		&i.Revision,
		&i.PidWithNamespace,
		&i.MountNamespaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
